export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const REGISTER_USER = "REGISTER";

export const PROFILE_VIEW_PAGE = "PROFILE_VIEW_PAGE";
export const PROFILE_EDIT_PAGE = "PROFILE_EDIT_PAGE";
export const REGISTER_CONTROL = "REGISTER_CONTROL";
export const LOST_PASSWORD_CONTROL = "LOST_PASSWORD_CONTROL";
export const PASSWORD_CHANGE = "PASSWORD_CHANGE";
export const PASSWORD_RESET = "PASSWORD_RESET";
export const NOTIFICATION_VIEW_PAGE = "NOTIFICATION_VIEW_PAGE";
export const GET_EMAIL = "GET_EMAIL";

export const PRODUCT_LIST = "PRODUCT_LIST";
export const PRODUCT_ADD = "PRODUCT_ADD";

export const STOCK_VIEW_PAGE = "STOCK_VIEW_PAGE";
export const ADD_DEVICE = "ADD_DEVICE";

export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const SHOPPING_CART = "SHOPPING_CART";

export const CONTACT_FORM = "CONTACT_FORM";

//action types belirlendi
