export default {
  login: "",
  register: "",
  profile: "",
  product: "",
  stock: "",
  productadd: "",
  profileedit: "",
  cart:[],
  shopping:"",
  password:"",
  device:"",
  token:"",
  email:"",
  contact:"",
  notification:[],
  lostpassword:"",
  email:"",
};
//default parametreler oluşturuldu
